import type { DiagramRenderer, RenderedDiagram } from '../../application/index.js'

/**
 * Graphviz implementation of the DiagramRenderer port, via `@hpcc-js/wasm-graphviz`.
 *
 * Loaded on demand, never bundled: the wasm binary is ~1.5 MB and RENDERERS.md
 * §7 puts it in the on-demand column. A note with no DOT block never pays for
 * it, and the dynamic import is what makes that true.
 *
 * Graphviz answers a bad graph by throwing, so every failure is caught and
 * returned as `{ ok: false }` carrying Graphviz's own message — the same
 * contract Mermaid honours, so a broken graph shows an inline error card with
 * its source still editable rather than taking the document down.
 *
 * Output is SVG produced by Graphviz itself. It is not passed through
 * DOMPurify: unlike a pasted `<svg>`, this markup is generated by the engine
 * from the source text rather than supplied by the clipboard. Labels are
 * escaped by Graphviz on the way in.
 */

type GraphvizEngine = { layout(source: string, format: string, engine: string): string }

/** One wasm instance for the document, created the first time a graph renders. */
let enginePromise: Promise<GraphvizEngine> | undefined

async function engine(): Promise<GraphvizEngine> {
  enginePromise ??= import('@hpcc-js/wasm-graphviz').then(
    (module) => module.Graphviz.load() as unknown as Promise<GraphvizEngine>,
  )
  return enginePromise
}

export class GraphvizRenderer implements DiagramRenderer {
  readonly languages = ['dot', 'graphviz'] as const

  async render(language: string, source: string): Promise<RenderedDiagram> {
    if (!this.languages.includes(language as 'dot')) {
      return { ok: false, message: `GraphvizRenderer cannot render "${language}"` }
    }

    const trimmed = source.trim()
    if (trimmed === '') return { ok: false, message: 'Graph source is empty' }

    try {
      const graphviz = await engine()
      const svg = graphviz.layout(trimmed, 'svg', 'dot')
      if (typeof svg !== 'string' || svg.trim() === '') {
        return { ok: false, message: 'Graphviz produced no output for this source' }
      }
      return { ok: true, markup: svg }
    } catch (error) {
      return { ok: false, message: error instanceof Error ? error.message : String(error) }
    }
  }
}
